config/routes.rb
Rails.application.routes.draw do
  root            to: 'pages#home'
  get 'contact',  to: 'pages#contact'
  get 'about',  to:   'pages#about'
  get 'skills',  to: 'pages#skills'
  get 'project',  to: 'pages#project'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render 
  end

  def contact
  end

  def about
  end

  def skills
  end

  def project
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webportfoliodeveloper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
  <%=render'shared/navbar'%>
    <%=yield%>
  <br>
  <br>
  <%=render'shared/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="aboutText">
    <h1>About me</h1>

    <p>I am a Full-Stack Software Developer who recently made a life switch from working with vulnerable families into coding.
    After spending number of years working as Function Family Therapist. I am ready for a new world of challenges. 
    During my time at Le Wagon, I have increased my knowledge and my execution in writing code. Currently, 
    I am working with a team of four on our final Ruby on Rails Prototype ‘Property Ai’ a site where buyers can 
    gain knowledge of the area which they intended to buy. I enjoy solving problems and passionate about working 
    collaboratively to make products. Looking forward to developing my skills furthure.
    </p>
  </div>


  <div class="AboutHistory"></div>
    <div class="aboutUnImage">
      <%=image_tag "undraw_about_me.svg" %>
  <div>
</div>

app/views/pages/contact.html.erb
<div class="container">
# form below
  <div class="contactForm"> 
    <h1>Contact me</h1>
  </div>
  <div class="contactImage">
    <%=image_tag "undraw_social_girl_562b 1.svg" %>
    <%=link_to"HOME", root_path%>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container"> 
    <div class="heroText"> 

        <h1><span id="banner-typed-info"></span></h1>
    </div>
    <div class="heroImage"> 
        <%=image_tag "undraw_dev_female.svg" %>
    </div>
</div>

app/views/pages/project.html.erb
<div class=container>
  <h1>Projects</h1>

   <div id="projectOne">
        <br>
        <%= image_tag "undraw_dev_female.svg", alt:"", width:400 %>
        <%= link_to "Home", root_path, class: "nav-link" %>
  </div>
        <br>
        <br>
    <div id="projectTwo">
        <br>
        <%= image_tag "undraw_dev_female.svg", alt:"", width:400 %>
        <%= link_to "Home", root_path, class: "nav-link" %>
    </div>
        <br>
        <br>
    <div id="projectThree">
        <br>
        <%= image_tag "undraw_dev_female.svg", alt:"", width:400 %>
        <%= link_to "Home", root_path, class: "nav-link" %>
    </div>
        <br>
        <br>
    <div id="projectFour">
        <br>
        <%= image_tag "undraw_dev_female.svg", alt:"", width:400 %>
        <%= link_to "Home", root_path, class: "nav-link" %>
    </div>
</div>

app/views/pages/skills.html.erb
<div class="container">
  <div class="skillsText">
    <br>
    <br>
    <p>The main area of my expertise is front end developer ( client side of the web).
    HTML, CSS,JS, building small and meduim web apps with Ruby on Rails, custom plugin, feature, animations and coding interactive layouts.
    Using Ruby on Rails as full stack developer .</p>
    <br>
  <div class="skillheader">
      <h1 class="skillheader"> Skills & Experinces</h1>
  </div>
  </div>
  <div class="skillUndraw">
      <%=image_tag "undraw_static_assets_rpm6 1.svg" %>
    </div>

</div>

app/views/shared/_footer.html.erb
  <div class="footer-links">
    <a href="https://github.com/lish90 " class="github"><i class="fab fa-github"></i></a>
    <a href="https://twitter.com/Lish901" class="twitter"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/alisha-m-40980416b/" class="linkedin"><i class="fab fa-linkedin"></i></a>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-bar" do%>
    <%= image_tag "iconmonstr-code-8.svg"%> 
  <% end %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Skills", skills_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to"Project", project_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link"%>
      </li>
      <li class= "nav-item dropdown">
       <%=image_tag "iconmonstr-code-fork-2.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right nav-item dropdown" aria-labelledby="navbarDropdown">
          <%= link_to "Home", root_path, class: "dropdown-item" %>
          <%= link_to "About", about_path, class: "dropdown-item" %>
          <%= link_to "Skills", skills_path, class: "dropdown-item" %>
          <%= link_to "Projects", project_path, class: "dropdown-item" %>
          <%= link_to "Contact", contact_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>